name = "Teawie the Mods"
author = "skyevg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b80d3ee74d66f416cb07cdfe022c2875146c5cf79d9b58ec82b75922e0e36f45"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
