name = "Teawie the Mods"
author = "skyevg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "207c17cc9e5e5204fb7eaf8330cd115b7060a10e6975ecaf2b9f6fbfc586e25e"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
unsup = "0.2.3"
