name = "Teawie the Mods"
author = "skyevg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "453b0b87c52a936e4325b21c408a5cb5005a40fb7c89fd0421e6a46e01cad27a"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
