[flavor_groups.ipn]
name = "Inventory Profiles Next"
description = "Inventory Profiles Next."
side = "client"
choices = ["ipn_off", {id = "ipn_on", default = true}]

[flavor_groups.recipe_viewer]
name = "Recipe Viewer"
description = "Which recipe viewer you'd like to use.\nI(skyevg) recommend EMI"
side = "client"
[[flavor_groups.recipe_viewer.choices]]
id = "no_recipe_viewer"
name = "None"
description = "No recipe viewer. Good if you want to use REI or similar."
[[flavor_groups.recipe_viewer.choices]]
id = "emi"
name = "EMI"
default = true
description = "EMI. Has recipe trees and is generally better(imo) but may have some mod compat issues."
[[flavor_groups.recipe_viewer.choices]]
id = "jei"
name = "JEI"
description = "JEI. Has less mod compat issues than EMI."

[metafile.jei]
flavors = ["jei", "emi"]
[metafile.emi]
flavors = "emi"

[metafile.inventory-profiles-next]
flavors = "ipn_on"
[metafile.libipn]
flavors = "ipn_on"